services:

  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: always
    # ports:
    # - "127.0.0.1:15432:5432"
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # POSTGRES_USER: postgres  # default
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: postgres  # used to define a different name for the default database
    volumes:
    - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
    - 18080:8080

volumes:
  pgdata:


